spring.application.name=swordmaster

# DB 드라이버 클래스
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 테이블 자동 생성/변경
spring.jpa.hibernate.ddl-auto=update

# 콘솔에 DB로 날아가는 SQL 쿼리 출력
spring.jpa.properties.hibernate.show_sql=true

# 출력되는 SQL 쿼리를 줄바꿈과 들여쓰기로 정렬
spring.jpa.properties.hibernate.format_sql=true

# SQL 쿼리가 자바 코드의 어느 클래스/메서드에 실행되는지를 쿼리문 맨 위에 주석으로 표시
spring.jpa.properties.hibernate.use_sql_comments=true


spring.profiles.active=local

#${JWT_SECRET}임시 값
jwt.secret=XfgNhoza7gT8O8NkqZiF7qx13xdfh/7OesGX0rxLFwM=
jwt.expiration-ms=3600000

# 구글 시트
game-data.sheet-id=19EYn3hOnV9NlvlI1Q-Pyvq1wPXYyOtEuvjvqVsDpK-4
game-data.gid.swords=132764007
game-data.gid.artifacts=813917840
